### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by ErixTheUncoder**
Made StudentPeerReview page have forms and fixed css on most of the website. Will make it look better afterwards

### CODE REVIEW

**Comment by JaxChoong** [comment]
can you make a the register button disappear after logging in

**Comment by ErixTheUncoder** [comment]
> can you make a the register button disappear after logging in

On which html page, I need some context. Meaning on every single html pages? Something that changes dynamically?

**Comment by JaxChoong** [comment]
> > can you make a the register button disappear after logging in
> 
> On which html page, I need some context. Meaning on every single html pages? Something that changes dynamically?

every single page has the nav bar right? so just do it in the layout.html or something and it should affect all

**Comment by CalvinChongg** [comment]
are we merging this?

**Comment by ErixTheUncoder** [comment]
I am merging

**Pull request merged**
