### PR TITLE
Database testing

### PR DESCRIPTION
**Pull request by JaxChoong**
i added a database.db file that acts as the database, with a USERS table in it, with the coloumns " id, username, password and position" in it. I have also added a databaseTest.py file to show how to cycle through the database/table/data.  Weird thing is that if u just click run/ use python debugger it doesnt work ( at least for me it shows cant find python 3.11), but if u go terminal and use "python3 databaseTest.py" it works flawlessly

### CODE REVIEW

**Comment by iKonicStixx** [comment]
we keeping the empty database.db right?

**Comment by JaxChoong** [comment]
its not empty tho?? but yes we are keeping this database.db

**Comment by iKonicStixx** [comment]
on my end it says "binary file not found."

**Comment by JaxChoong** [comment]
did u download the extension on vscode? how did u test this?

**Pull request merged**
