### PR TITLE
365 login

### PR DESCRIPTION
**Pull request by JaxChoong**
features:
1) Added microsoft 365 email login
2) Checks for user's email if its mmu email
3) Adds user's roles according to their email 
4) Adds students into database when they login 
5) Lecturers can import students and make accounts for them.

### CODE REVIEW

**Comment by CalvinChongg** [comment]
you know i could have done 2. and 3. right?

**Comment by JaxChoong** [comment]
you snooze u lose

**Comment by CalvinChongg** [comment]
did you merge the backend pull req first?

**Comment by JaxChoong** [comment]
:donkey-1:

**Comment by CalvinChongg** [comment]
aight nice no conflict

**Pull request merged**
